server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: git@github.com:zhangshuai-z/springcloud-config.git #github仓库名称
          #搜索目录
          search-paths:
            - springcloud-config
      #读取分支
      label: main
eureka:
  client:
    # 是否将自己注册到EurekaServer默认为true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息 默认为true 单节点无所谓。集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
  instance:
    prefer-ip-address: true #访问路径可以显示ip地址
    lease-renewal-interval-in-seconds: 1 # Eureka客户端向服务端发送心跳的时间间隔，单位是秒（默认30秒）
    lease-expiration-duration-in-seconds: 2 # Eureka服务端在收到最后一次心跳后等待时间上限，单位是秒（默认90秒），超时将剔除服务
    hostname: cloud-gateway-service