server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务的名称进行路由
      routes:
        - id: payment_routh #路由的id，没有固定的规则但要求唯一、建议配合服务名
#          uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/getPaymentById/**  #断言，路径相匹配的进行路由

        - id: payment_routh2 #路由的id，没有固定的规则但要求唯一、建议配合服务名
#          uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**  #断言，路径相匹配的进行路由
#            - After=2022-08-02T09:38:36.945+08:00[Asia/Shanghai]
#            - Cookie=username,zhangs
#            - Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性并且值为正数的正则表达式

eureka:
  client:
    # 是否将自己注册到EurekaServer默认为true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息 默认为true 单节点无所谓。集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
  instance:
    prefer-ip-address: true #访问路径可以显示ip地址
    lease-renewal-interval-in-seconds: 1 # Eureka客户端向服务端发送心跳的时间间隔，单位是秒（默认30秒）
    lease-expiration-duration-in-seconds: 2 # Eureka服务端在收到最后一次心跳后等待时间上限，单位是秒（默认90秒），超时将剔除服务
    hostname: cloud-gateway-service